name: Artifact Demo

on: push

jobs:
  build:
     runs-on: ubuntu-latest

     steps:
       - name: create file
         run:
             mkdir temp
             echo "alpa" > temp/alpha.html

       - name: Upload artifact
         uses: action/upload-artifact@v4
         with:
           name: files
           path: temp/
